language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - db=postgres
    - db=mysql
    - db=sqlite3

before_script:
    - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install
    - psql -c 'create database app_test' -U postgres
    - mysql -u travis -e 'create database app_test'
    - environment=test db.sh db:migrate

script:
    - phpunit --configuration phpunit.xml test
